library(survey)
library(jtools)
library(psych)

#don't run too big?
# pairs.panels(data2[c(155,157,159,160,183,161,162,164,166,167,171,172,173,175,178,179)], gap = 0) #correlation matrix 



# Logistic Regression  - DV1 GTEV, 2000-2010
fit_DV1 <- svyglm(GT_EVERHEARD ~ INSURED+EDUCATED+EMPL+INPOV+MAR+REPRODHIST+SCREENED+FAMHISTCANCER+USUAL+HHDELAY_COST+HHDELAY_NOTCOST+
                    BLACK+BLACK*INSURED+BLACK*EDUCATED+BLACK*EMPL+BLACK*INPOV+BLACK*MAR+BLACK*REPRODHIST+BLACK*SCREENED+BLACK*FAMHISTCANCER+BLACK*USUAL+BLACK*HHDELAY_COST+BLACK*HHDELAY_NOTCOST,
                  design= df ,family=binomial())


summ(fit_DV1, confint= TRUE, exp = TRUE)

# Logistic Regression  - DV2 GT | GTEV, 2000-2010
fit_DV2 <- svyglm(GT ~ INSURED+EDUCATED+EMPL+INPOV+MAR+REPRODHIST+SCREENED+FAMHISTCANCER+USUAL+HHDELAY_COST+HHDELAY_NOTCOST+
                    BLACK+BLACK*INSURED+BLACK*EDUCATED+BLACK*EMPL+BLACK*INPOV+BLACK*MAR+BLACK*REPRODHIST+BLACK*SCREENED+BLACK*FAMHISTCANCER+BLACK*USUAL+BLACK*HHDELAY_COST+BLACK*HHDELAY_NOTCOST,
                  design= subset(df, GT_EVERHEARD==1),family=binomial())


summ(fit_DV2, confint = TRUE, exp = TRUE)

#logistic regression - DV2b | SCREEEND & GTEV
fit_DV2b <- svyglm(GT ~ INSURED+EDUCATED+EMPL+INPOV+MAR+REPRODHIST+FAMHISTCANCER+USUAL+HHDELAY_COST+HHDELAY_NOTCOST+
                    BLACK+BLACK*INSURED+BLACK*EDUCATED+BLACK*EMPL+BLACK*INPOV+BLACK*MAR+BLACK*REPRODHIST+BLACK*FAMHISTCANCER+BLACK*USUAL+BLACK*HHDELAY_COST+BLACK*HHDELAY_NOTCOST,
                  design= subset(df, SCREENED==1 & GT_EVERHEARD==1),family=binomial())


summ(fit_DV2b, confint = TRUE, exp = TRUE)



# Logistic Regression  - DV3 GT, 2015 

fit_DV3 <- svyglm(GT ~ INSURED+EDUCATED+EMPL+INPOV+MAR+REPRODHIST+SCREENED+FAMHISTCANCER+USUAL+HHDELAY_COST+HHDELAY_NOTCOST+
                    BLACK+BLACK*INSURED+BLACK*EDUCATED+BLACK*EMPL+BLACK*INPOV+BLACK*MAR+BLACK*REPRODHIST+BLACK*SCREENED+BLACK*FAMHISTCANCER+BLACK*USUAL+BLACK*HHDELAY_COST+BLACK*HHDELAY_NOTCOST,
                  design=df4,family=binomial())

summ(fit_DV3, confint = TRUE, exp=TRUE)



#logistic regression: DV4 - 2015 GTdiscdr

fit_DV4 <- svyglm(GT_DISCDR ~ INSURED+EDUCATED+EMPL+INPOV+MAR+REPRODHIST+SCREENED+FAMHISTCANCER+USUAL+HHDELAY_COST+HHDELAY_NOTCOST+
                    BLACK+BLACK*INSURED+BLACK*EDUCATED+BLACK*EMPL+BLACK*INPOV+BLACK*MAR+BLACK*REPRODHIST+BLACK*SCREENED+BLACK*FAMHISTCANCER+BLACK*USUAL+BLACK*HHDELAY_COST+BLACK*HHDELAY_NOTCOST,
                  design=df4,family=binomial())

summ(fit_DV4, confint = TRUE, exp=TRUE)





#POISSON REGRESSION

# POISSON Regression  - DV1 GTEV, 2000-2010
fit_DV1p <- svyglm(GT_EVERHEARD ~ INSURED+EDUCATED+EMPL+INPOV+MAR+REPRODHIST+SCREENED+FAMHISTCANCER+USUAL+HHDELAY_COST+HHDELAY_NOTCOST+
                    BLACK+BLACK*INSURED+BLACK*EDUCATED+BLACK*EMPL+BLACK*INPOV+BLACK*MAR+BLACK*REPRODHIST+BLACK*SCREENED+BLACK*FAMHISTCANCER+BLACK*USUAL+BLACK*HHDELAY_COST+BLACK*HHDELAY_NOTCOST,
                  design= df ,family=poisson())


summ(fit_DV1p, confint= TRUE, exp = TRUE)

# POISSON Regression  - DV2 GT | GTEV, 2000-2010
fit_DV2p <- svyglm(GT ~ INSURED+EDUCATED+EMPL+INPOV+MAR+REPRODHIST+SCREENED+FAMHISTCANCER+USUAL+HHDELAY_COST+HHDELAY_NOTCOST+
                    BLACK+BLACK*INSURED+BLACK*EDUCATED+BLACK*EMPL+BLACK*INPOV+BLACK*MAR+BLACK*REPRODHIST+BLACK*SCREENED+BLACK*FAMHISTCANCER+BLACK*USUAL+BLACK*HHDELAY_COST+BLACK*HHDELAY_NOTCOST,
                  design= subset(df, GT_EVERHEARD==1),family=poisson())


summ(fit_DV2p, confint = TRUE, exp = TRUE)

#POISSON regression - DV2b | SCREENED & GTEV
fit_DV2bp <- svyglm(GT ~ INSURED+EDUCATED+EMPL+INPOV+MAR+REPRODHIST+FAMHISTCANCER+USUAL+HHDELAY_COST+HHDELAY_NOTCOST+
                     BLACK+BLACK*INSURED+BLACK*EDUCATED+BLACK*EMPL+BLACK*INPOV+BLACK*MAR+BLACK*REPRODHIST+BLACK*FAMHISTCANCER+BLACK*USUAL+BLACK*HHDELAY_COST+BLACK*HHDELAY_NOTCOST,
                   design= subset(df, SCREENED==1 & GT_EVERHEARD==1),family=binomial())


summ(fit_DV2bp, confint = TRUE, exp = TRUE)



# POISSON Regression  - DV3 GT, 2015 

fit_DV3p <- svyglm(GT ~ INSURED+EDUCATED+EMPL+INPOV+MAR+REPRODHIST+SCREENED+FAMHISTCANCER+USUAL+HHDELAY_COST+HHDELAY_NOTCOST+
                    BLACK+BLACK*INSURED+BLACK*EDUCATED+BLACK*EMPL+BLACK*INPOV+BLACK*MAR+BLACK*REPRODHIST+BLACK*SCREENED+BLACK*FAMHISTCANCER+BLACK*USUAL+BLACK*HHDELAY_COST+BLACK*HHDELAY_NOTCOST,
                  design=df4,family=poisson())

summ(fit_DV3p, confint = TRUE, exp=TRUE)

# POISSON Regression  - DV3a GT, 2015 | GT_DISCDR

fit_DV3bp <- svyglm(GT ~ INSURED+EDUCATED+EMPL+INPOV+MAR+REPRODHIST+SCREENED+FAMHISTCANCER+USUAL+HHDELAY_COST+HHDELAY_NOTCOST+
                     BLACK+BLACK*INSURED+BLACK*EDUCATED+BLACK*EMPL+BLACK*INPOV+BLACK*MAR+BLACK*REPRODHIST+BLACK*SCREENED+BLACK*FAMHISTCANCER+BLACK*USUAL+BLACK*HHDELAY_COST+BLACK*HHDELAY_NOTCOST,
                   design=subset(df4, GT_DISCDR==1), family=poisson())

summ(fit_DV3bp, confint = TRUE, exp=TRUE)

#POISSON regression: DV4 - 2015 GT_DISCDR

fit_DV4p <- svyglm(GT_DISCDR ~ INSURED+EDUCATED+EMPL+INPOV+MAR+REPRODHIST+SCREENED+FAMHISTCANCER+USUAL+HHDELAY_COST+HHDELAY_NOTCOST+
                    BLACK+BLACK*INSURED+BLACK*EDUCATED+BLACK*EMPL+BLACK*INPOV+BLACK*MAR+BLACK*REPRODHIST+BLACK*SCREENED+BLACK*FAMHISTCANCER+BLACK*USUAL+BLACK*HHDELAY_COST+BLACK*HHDELAY_NOTCOST,
                  design=df4,family=poisson())

summ(fit_DV4p, confint = TRUE, exp=TRUE)


plot_summs(fit_DV1, fit_DV1p, exp=TRUE, 
           model.names = c("Logistic", "Poisson"))

plot_summs(fit_DV1, fit_DV1p, exp=TRUE, omit.coefs = c("REPRODHIST", "SCREENED"),
           model.names = c("Logistic", "Poisson"))








